config/routes.rb
Rails.application.routes.draw do
  resources :places # Resources needed to be updated for place/images
  get 'about/index'

  get 'reviews/index'

  get 'welcome/index'
  resources :restaurants do
    resources :reviews
  end
  
  root 'welcome#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
   mount_uploader :image, ImageUploader
    validates_processing_of :image
    validate :image_size_validation
     
    # The module is for the mount_uploader which is required for the files and allows for input validation 
     
    private
      def image_size_validation
        errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
      end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
has_many :reviews, dependent: :destroy
validates :name, presence: true, length: { minimum: 5 }
validates :name, length: { maximum: 50 }
validates :location, presence: true, length: {maximum: 60}
validates :description, presence: true, length: { minimum: 50}
validates :description, length: { maximum: 255 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :commenter, presence: true, length: { minimum: 1 }
  validates :rating, presence: true, format: { with: /[0-9]+(\.[0-9][0-9]?)?/ }
  validates :rating, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validates :review, presence: true, length: { minimum: 25 }
  validates :review, length: { maximum: 255 }
end

app/controllers/about_controller.rb
class AboutController <ApplicationController
  def list
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  
  # Controller is auto generated by carrierwave

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :image)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    def index
        @restaurants = Restaurant.all
    end
    
    def show
        @restaurant = Restaurant.find(params[:id])
    end
    
    def new
        @restaurant = Restaurant.new
    end
    
    def create
        @restaurant = Restaurant.new(restaurant_params)
            
        if @restaurant.save
            redirect_to @restaurant
        else
            render 'new'
        end
    end
    
    def edit
        @restaurant = Restaurant.find(params[:id])
    end
    
    def update
        @restaurant = Restaurant.find(params[:id])
        
        if @restaurant.update(restaurant_params)
               redirect_to @restaurant
        else
            render 'edit'
        end
    end
    
    def destroy
        @restaurant = Restaurant.find(params[:id])
        @restaurant.destroy
        redirect_to restaurants_path
    end

private
def restaurant_params
    params.require(:restaurant).permit(:name,:description,:location)
end

end

app/controllers/review_controller.rb
class ReviewController < ApplicationController
    def show
        @review = Review.find(params[:id])
    end
    
    def new
        @review = Review.new
    end
    
    def create
        @review = Review.new(review_params)
        
        if @review.save
            redirect_to @review
        else
            render 'new'
        end
    end
    
    def index
        @reviews = Review.all
    end
    
    def edit
        @review = Review.find(params[:id])
    end
    
    def update
        @review = Review.find(params[:id])
        
        if @review.update(review_params)
               redirect_to @review
        else
            render 'edit'
        end
    end
    
    def destroy
        @review = Article.find(params[:id])
        @review.destroy
        redirect_to review_path
    end
    
    
end

private
def review_params
    params.require(:review).permit(:title, :text)
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def index
        @reviews = Review.all
    end
    
    def create
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review = @restaurant.reviews.create(review_params)
        redirect_to restaurant_path(@restaurant)
    end
    
    def new
      @review = @restaurant.review.build
    end
    
    
    def destroy
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review = @restaurant.reviews.find(params[:id])
        @review.destroy
        redirect_to restaurant_path(@restaurant)
    end
    
    def edit
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review=Review.find(params[:id])
    end
    
    def update
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review = @restaurant.reviews.find(params[:id])
        
        if @review.update(review_params)
            redirect_to restaurant_path(@restaurant)
        else
            render 'edit'
        end
    end    
    
    private
    def review_params
        params.require(:review).permit(:commenter, :review, :rating)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def list
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<head>
    <meta name="description" content="Group Number 9" />
	<meta charset="UTF-8">
</head>

<div id = "shell">    
        
 <h1 id = "name"><%= link_to 'Caupona Adventures', welcome_index_path %></h1>
    <p>
        <%= link_to 'Home', welcome_index_path  %> |
	    <%= link_to 'Restaurants', restaurants_path %>
    </p>
    <h3>Number 9 Large</h3>
    
<div class = "about">
<p>
    Caupona Adventures is a team-driven project developed and designed by the group Number 9 large.
    It aims to provide a user friendly website that allows users to review restaurants and rate them
    on a 1-5 scale.<div class = "link"> 
    <p>We also offer a <a href = "https://group-9-project-davidaniel91.c9users.io/restaurants">
        wide list of different restaurants</a> that you could choose to either edit, destroy, comment or simply 
        read!!</div></p>
        </p>
</div>        
</div>

<footer>
    &copy; Copyright 2017, Caupona Adventures (Group 9)
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CauponaAdventures</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_for @place, html: { multipart: true } do |f| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="cat">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="cat">
    <br>
    <%= f.label :image %><br>
    <!--Notice how file_field is required for images-->
    <%= f.file_field :image %> 
  </div>

  <div class="cat">
    <br>
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<div id= "shell">
<h1>Editing Place</h1>

<%= render 'form', place: @place %>
<div id = "b2">
<%= link_to 'Back', places_path %>
</div>
</div>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<div id= "shell">
  
<h1 id = "name"><%= link_to 'Caupona Adventures', welcome_index_path %></h1><br>

<h1>Places</h1>

<p>
    Places is a section for users to upload their pictures of their favorite restaurants<br>
            Please feel free to upload, edit, and remove any pictures<br>
              All we ask is that the pictures are restaurant related!
</p>

<a color=#F0E68C href=places/new class="button button4">Add a new picture</a>
<head>
  <title>Places</title>
  <meta charset="UTF-8">
</head>


<table width="100%" valign="top">
  <thead>
    <tr>
      <th class = "restaurant">Name</th>
      <th class = "restaurant">Image</th>
      <th class = "restaurant" colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr class = "listing">
        <td><%= link_to place.name, place_path(place) %></td>
        <td><%= place.image %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id = "b2">
<%= link_to 'Back', restaurants_path %>
</div>
</div>

app/views/places/new.html.erb
<div id= "shell">
<h1>New Place</h1>

<%= render 'form', place: @place %>
<div id = "b2">
<%= link_to 'Back', places_path %>
</div>
</div>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<div id= "shell">

<p>
  <strong>Name:</strong><br>
  <%= @place.name %>
</p>

<p>
  <strong>Image:</strong><br>
  <%= image_tag @place.image.url %>
</p>

<div id = "b2">
<%= link_to 'Edit', edit_place_path(@place) %> ||
<%= link_to 'Back', places_path %>
</div>
</div>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
    <div class ="cat">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    </div>
    <div class= "cat">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
    </div>
    <div class ="cat">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
    </div>

<p>
    <%= f.submit %>
</p>
<% end %>

<% if @restaurant.errors.any? %>
 <div id="error_explanation">
<div class="alert">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
     <%= pluralize(@restaurant.errors.count, "error") %> prohibited
     this restaurant from being saved:
     <% @restaurant.errors.full_messages.each do |msg| %>
      <li id= "error_explanation"><%= msg %></li>
     <% end %>
</div>
</div>
     
<% end %>
<div id = "b2">
<%= link_to 'Back', restaurants_path %>
</div>

app/views/restaurants/edit.html.erb
<div id="shell">
     <p>
        <%= link_to 'Home', welcome_index_path %> |
	    <%= link_to 'Restaurants', restaurants_path %>
    </p>

<h1>Editing Restaurant</h1>
 
<%= render 'form' %>
</div>
<footer>
    &copy; Copyright 2017, Caupona Adventures (Group 9)
</footer>

app/views/restaurants/index.html.erb
<head>
  <title>Restaurants</title>
  <meta charset="UTF-8">
</head>

 
<div id= "shell">

<h1 id = "name"><%= link_to 'Caupona Adventures', welcome_index_path %></h1><br>

<div class = "restaurant">
    

 <a color=#F0E68C href=restaurants/new class="button button4">Add a New Restaurant</a> ||
 <a color=#F0E68C href=places class="button button4">View User Pictures</a>

<table width="100%" valign="top">
  <tr>
    <th class = "restaurant">Restaurant</th><br>
    <br><th class = "restaurant">Location</th>
    <th class = "restaurant">Description</th>
    <th colspan="2">Actions</th>
  </tr>
  
  
  <% @restaurants.each do |restaurant| %>
  
    <tr class = "listing">
      <td><%= link_to restaurant.name, restaurant_path(restaurant) %></td>
      <td><%= restaurant.location %></td>
      <td><%= restaurant.description%></td>
      <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
      <td><%= link_to 'Destroy', restaurant_path(restaurant), method: :delete, 
      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
</div>
<div id=b2>
<%= link_to 'Back', welcome_index_path %>
</div>
</div>

<div>
  <footer>
    &copy; Copyright 2017, Caupona Adventures (Group 9)
</footer>
</div>

app/views/restaurants/new.html.erb
<header>
    <title>New Restaurant</title>
   
	<meta charset="UTF-8">
</header>

<div id="shell">
 <p>
        <%= link_to 'Home', welcome_index_path %> |
	    <%= link_to 'Restaurants', restaurants_path %>
    </p>
<h1>New Restaurant</h1>
<%= render 'form' %>
</div>
<footer>
    &copy; Copyright 2017, Caupona Adventures (Group 9)
</footer>

app/views/restaurants/show.html.erb
    
<div id= case>  
<p>
        <%= link_to 'Home', welcome_index_path %> |
	      <%= link_to 'Restaurants', restaurants_path %>
    </p>
    <h1>
    <%=@restaurant.name%> <br>
    <h3>
    <%=@restaurant.location %> 
    </h3>
    <div id= desc>
    <%= @restaurant.description %>
    </div>


<table class=center width="100%" valign="top">
    <tr class = "listing">
    <th class = "Name">Name</th><br>
    <br><th class = "Review">Review</th>
    <th class = "Rating">Rating</th>
    <th class = "Delete">Delete</th>
    <th class = "Edit">Edit</th>
    </tr>
  
<% @restaurant.reviews.each do |review| %>
<tr class >
<p>
  <td><%= review.commenter %></td>
  <td><%= review.review %></td>
  <td><%= review.rating %></td>
  <td><%= link_to 'Delete Review', [review.restaurant, review],
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
  <td><%= link_to 'Edit Review', edit_restaurant_review_path(review.restaurant, review) %></td>
</p>
</tr>
<% end %>
</table>
<%= render 'reviews/form' %>



<div id = "b2">
<%= link_to 'Back', restaurants_path %>
</div>
</div>
<footer> 
  Copyright 2017, Caupona Adventures (Group 9)
</footer>

app/views/review/index.html.erb
<h1>Listing reviews</h1>
 <%= link_to 'New review', new_review_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @reviews.each do |review| %>
    <tr>
      <td><%= review.title %></td>
      <td><%= review.text %></td>
      <td><%= link_to 'Show', review_path(review) %></td>
      <td><%= link_to 'Edit', edit_review_path(review) %></td>
    </tr>
  <% end %>
</table>

app/views/review/list.html.erb
<h1>Listing articles</h1>
 <%= link_to 'New review', new_review_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @reviews.each do |review| %>
    <tr>
      <td><%= review.title %></td>
      <td><%= review.text %></td>
      <td><%= link_to 'Show', review_path(review) %></td>
      <td><%= link_to 'Edit', edit_review_path(review) %></td>
    </tr>
  <% end %>
</table>

app/views/review/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', review_path %>

app/views/review/restaurants.html.erb
<h1>Restaurants</h1>

<%= @review.each do |f| %> 
    <%= f.title %>
    <!-- Implement multiple reviews later (depending on what "text"
    will be)-->
    <% f.text %>
    <!-- This might be where the picture goes later. f.picture possibly.
        CSS might be used for the pictures.-->
    <%= link_to 'show', show_review_path  %>
    <%= link_to 'update', edit_review_path %>
    <!-->This is also a way to do a comment. Use !-- then enter tab. </!-->
<%= end %>

app/views/review/show.html.erb
<p>
    <strong>title</strong>
    <%= @review.title %>
</p>

<p>
    <strong>text</strong>
    <%= @review.text %>
</p>
<%= link_to 'Restaurant List', review_path %>

app/views/reviews/_form.html.erb
<%= form_for([@restaurant, @restaurant.reviews.build]) do |f| %>

     <p>
      The review must fill these requirements to be saved:
      <p id=error>Commenter Field cannot be empty <br>
      Rating must be between 1 and 5<br>
      Review has a minimum requirement of 25 characters</p>
</p>
       
    
<p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %><br>
    <%= f.label :rating %><br>
    <%= f.text_field :rating %><br>
    <%= f.label :review %><br>
    <%= f.text_area :review %>
    
    

<p>
    <%= f.submit %>
</p>
<% end %>

app/views/reviews/_review.html.erb
<p>
    <strong>Commenter:</strong>
    <%= review.commenter %>
</p>

<p>
       <strong>Review:</strong>
       <%= review.review %>
</p>

<p>
    <strong>Rating:</strong>
    <%= review.rating %>
</p>

<p>
    <%= link_to 'Destroy Review', [review.restaurant, review],
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %>
</p>

app/views/reviews/edit.htm.erb
<header>
    <%= link_to 'Home', welcome_index_path %> |
	<%= link_to 'Restaurants', restaurant_index_path %>
</header>

<h1>Editing review</h1>
 
 <%= render 'form' %>
 
<!-- Removed Link_to due to it creating a duplicate back button -->

<footer>
    &copy; Copyright 2017, Caupona Adventures (Group 9)
</footer>

app/views/reviews/edit.html.erb
<header>
       <p>
        <%= link_to 'Home', welcome_index_path %> |
	    <%= link_to 'Restaurants', restaurants_path %>
    </p>
	<meta charset="UTF-8">
</header>

 <div id="shell">
<h1>Editing review</h1>
<%= form_for @review, url:restaurant_review_path  do |f| %>

    <% if @review.errors.any? %>
     <div id="error_explanation">
       <h2>
         <%= pluralize(@review.errors.count, "error") %> prohibited
         this review from being saved:
       </h2>
        <ul>
         <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
         <% end %>
        </ul>
     </div>
    <% end %>
    
<p>
    <%= f.label :Commenter %><br>
    <%= f.text_field :commenter %>
</p>

<p>
    <%= f.label :Rating %><br>
    <%= f.text_field :rating %>
</p>


<p>
    <%= f.label :Review %><br>
    <%= f.text_area :review %>
</p>



<p>
    <%= f.submit %>
</p>
<% end %>

<div id = "b1">
<%= link_to 'Back', restaurants_path %>
</div>

</div>
<footer>
    &copy; Copyright 2017, Caupona Adventures (Group 9)
</footer>

app/views/reviews/index.html.erb
<h1>Reviews</h1>
 <head>
    <title>Caupona Adventures</title>
    <meta name="description" content="Group Number 9" />
	<meta charset="UTF-8">
</head>

<header>
</header>

<table>
    <tr>
        <th>Commenter</th>
        <th>Review</th>
        <th>Rating</th>
    </tr>
<% @review.each do |review| %>
<tr>
    <td><%= link_to 'Edit', edit_restaurant_review_path(review) %></td>
    <td><%= link_to 'Destroy', destroy_restaurant_review_path(review)%></td>
</tr>

<% end %>
</table>

app/views/reviews/new.html.erb
<header>
    <title>New Review</title>
    <p>
        <%= link_to 'Home', welcome_index_path %> |
	    <%= link_to 'Restaurants', restaurants_path %>
    </p>
	<meta charset="UTF-8">
</header>

<h1>New Review</h1>

<%= render 'review' %>


<footer>
    &copy; Copyright 2017, Caupona Adventures (Group 9)
</footer>

app/views/reviews/show.html.erb
<header>
    <title>Your Review</title>
    <p>
        <%= link_to 'Home', welcome_index_path %> |
	    <%= link_to 'Restaurants', restaurants_path %>
    </p>
	<meta charset="UTF-8">
</header>

<h1>Review</h1>

<%= render 'form' %>

app/views/welcome/index.html.erb
<head>
    <title>Caupona Adventures</title>
    <meta name="description" content="Group Number 9" />
	<meta charset="UTF-8">
</head>

  
<div id= case>
<table align = "center" , border = "1">
  <tr>
  <th><h1 id="center">Caupona Adventures</h1></th>
  </tr>
      <p>
        <%= link_to 'About Us', controller: 'about' %> |
	    <%= link_to 'Restaurants', restaurants_path %>
    </p>
</table>
  <!--
    <div class = "links">
    <ul>
	<li class = "link1"><%= link_to 'List of all Restaurants',controller: 'restaurants' %> </li>
	<li class = "link2"><%= link_to 'About us', controller: 'about'%></li>
	</ul>
	</div>
    -->


<p>
    <strong>Preview Review</strong><br>
    
    <strong>Restaurant:</strong> Surfside<br>         
    <strong>Location:</strong> P. Sherman 42 Wallaby Way, Sidney<br>
    <img>
    <%= image_tag("https://static.pexels.com/photos/51136/pexels-photo-51136.jpeg", :alt => "rss feed") %>
    </img>
    
    <br><strong>Review:</strong> A beautiful restaurant right on the ocean front and also features a large <br>
    fish tank with exotic fish!<br>
    <strong>Rating:</strong> 4.5
</p>
</div>


<footer id="footer">
    &copy; Copyright 2017, Caupona Adventures (Group 9)
</footer>